# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

euler <- function(c, d, kappa, tau, q, subdiv = 100L, eps_abs = 1e-14, eps_rel = 1e-14) {
    .Call('_gbeta_euler', PACKAGE = 'gbeta', c, d, kappa, tau, q, subdiv, eps_abs, eps_rel)
}

